apiVersion: 1

datasources:
  # InfluxDB datasource
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    user: admin
    secureJsonData:
      password: admin123456
      token: my-super-secret-auth-token
    jsonData:
      version: Flux
      organization: monitoring
      defaultBucket: telegraf
      tlsSkipVerify: true
    isDefault: true

  # PostgreSQL datasource
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: monitoring
    user: postgres
    secureJsonData:
      password: postgres123
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false